### ISSUE TITLE
datastore.discovery does not distinguish between different datastore types

### ISSUE THREAD

**Issue by S-O** [dav3860/vmbix#19]
`zabbix_get -s 127.0.0.1 -p 12053 -k 'datastore.discovery'`

```
Exception in thread "Thread-3" java.lang.ClassCastException: com.vmware.vim25.NasDatastoreInfo cannot be cast to com.vmware.vim25.VmfsDatastoreInfo
        at net.djarvur.vmbix.VmBix$Connection.getDatastores(Unknown Source)
        at net.djarvur.vmbix.VmBix$Connection.checkAllPatterns(Unknown Source)
        at net.djarvur.vmbix.VmBix$Connection.run(Unknown Source)
```

Using vSphere Perl SDK I can see that a Datastore Object has a Property 'summary' of type 'DatastoreSummary'. It has a field named 'type' which can have a value which is not 'VMFS'.
In my case it is 'NFS'. Maybe this can help you.

**Comment by acxadoom** [comment]
Hi I have fixed this issue, see into open issue the resolution.

**Comment by dav3860** [comment]
Hi,
I've just uploaded the version 2.0 which should fix this.
