### ISSUE TITLE
No VCSA support?

### ISSUE THREAD

**Issue by hetzbh** [dav3860/vmbix#53]
I'm trying to install the latest version of vmbix on my lab. I'm using VCSA 6.5 as well as few ESXI 6.5 hosts..
When using the vmbix command to connect to the esxi url (example: https://esxi1/sdk ) it works. However, when I try to connect to the VCSA (http://vcsa/sdk) it spits the error "Cannot connect to the VMWare SDK URL". Here is the full output.

`# vmbix -P 12050 -u "administrator@vsphere.local" -p "pass123" -s "https://vcsa/sdk/"
log4j:WARN No appenders could be found for logger (com.vmware.vim25.ws.XmlGenDom).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.vmware.vim25.InvalidLogin
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:219)
        at com.vmware.vim25.ws.XmlGenDom.parseSoapFault(XmlGenDom.java:147)
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:105)
        at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:212)
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:93)
        at com.vmware.vim25.ws.VimStub.login(VimStub.java:1732)
        at com.vmware.vim25.mo.SessionManager.login(SessionManager.java:153)
        at com.vmware.vim25.mo.ServiceInstance.login(ServiceInstance.java:238)
        at com.vmware.vim25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:131)
        at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:104)
        at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:94)
        at net.dav3860.VmBix.updateConnection(VmBix.java:435)
        at net.dav3860.VmBix.server(VmBix.java:489)
        at net.dav3860.VmBix.main(VmBix.java:234)
13:20:21.191 [main] ERROR net.dav3860.VmBix - Cannot connect to the VMWare SDK URL
13:20:21.197 [Thread-0] INFO net.dav3860.VmBix - Shutting down
13:20:21.197 [Thread-0] ERROR net.dav3860.VmBix - Error disconnecting: java.lang.NullPointerException
13:20:21.197 [Thread-0] INFO net.dav3860.VmBix - Shutted down
`

**Comment by dav3860** [comment]
Hi, VMBix supports VCSA 6.5. You may see an InvalidLogin error because of the VCSA SSO password policy. Are you sure that you are able to connect to the VI client with these credentials ?
What is your VMBix version ? Can you try to create a vmbix config file and use it with "-c" instead of passing arguments in the command line ?

**Comment by hetzbh** [comment]
Yes, I just found out, my original password had a ! in it, so it created problems, so I created a read only account, looks like this works ;)
